import { Box, Heading, Stack, Text, VStack } from '@chakra-ui/layout'
import Head from 'next/head'
import Layout from '../components/Layout'

const Home = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box maxW="100vw" minH="100vh">
        <Stack as="main" mt="8" spacing={8}>
          <Heading>Lorem ipsum</Heading>
          <Text>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta quibusdam sit et inventore laborum autem quisquam dolore fugit exercitationem in natus labore doloribus, qui similique debitis quos! Placeat, molestias quas.
          </Text>
          <Text>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta quibusdam sit et inventore laborum autem quisquam dolore fugit exercitationem in natus labore doloribus, qui similique debitis quos! Placeat, molestias quas.
          </Text>
          <Heading>Lorem ipsum</Heading>
          <Text>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta quibusdam sit et inventore laborum autem quisquam dolore fugit exercitationem in natus labore doloribus, qui similique debitis quos! Placeat, molestias quas.
          </Text>
          <Text>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta quibusdam sit et inventore laborum autem quisquam dolore fugit exercitationem in natus labore doloribus, qui similique debitis quos! Placeat, molestias quas.
          </Text>
          <Heading>Lorem ipsum</Heading>
          <Text>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta quibusdam sit et inventore laborum autem quisquam dolore fugit exercitationem in natus labore doloribus, qui similique debitis quos! Placeat, molestias quas.
          </Text>
          <Text>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta quibusdam sit et inventore laborum autem quisquam dolore fugit exercitationem in natus labore doloribus, qui similique debitis quos! Placeat, molestias quas.
          </Text>
        </Stack>
      </Box>

    </Layout>
  )
}
export default Home
